# Generated by Django 3.0.4 on 2020-03-16 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('shop_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shops',
            },
        ),
        migrations.AddConstraint(
            model_name='shopmodel',
            constraint=models.UniqueConstraint(fields=('shop_number', 'user'), name='unique_shop'),
        ),
    ]
